default_language_version:
  python: python3

repos:
  # ✅ Lokaler Hook für pytest mit Flask in eigener Umgebung
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest
        language: python
        entry: pytest -q
        additional_dependencies:
          - pytest==8.4.2
          - Flask>=3.0
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

  # ✅ Code-Formatter Black
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: ["--line-length=88"]

  # ✅ Code-Checker Flake8
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==24.8.19

  # ✅ Standard-Hooks für Whitespace, Merge-Konflikte usw.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: mixed-line-ending

  # ✅ Commit-Message-Policy (bleibt wie bisher)
  - repo: local
    hooks:
      - id: commit-msg-policy
        name: commit message policy
        language: python
        entry: python3 .git_hooks/commit-msg-policy.py
        stages: [commit-msg]
        pass_filenames: true
