# .pre-commit-config.yaml
default_language_version:
  python: python3

repos:
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest
        entry: python3 -m pytest -q
        language: system
        types: [python]
        stages: [pre-commit]
        pass_filenames: false
        always_run: true